#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# admin_login:
#     path: /login
#     controller: App\Controller\Security\AdminController::adminLogin

admin_login_check:
    path: /login_check

logout:
    path: /logout
